// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.jsx";
import * as $_middleware from "./routes/_middleware.jsx";
import * as $api_health from "./routes/api/health.jsx";
import * as $index from "./routes/index.jsx";

const manifest = {
  routes: {
    "./routes/_app.jsx": $_app,
    "./routes/_middleware.jsx": $_middleware,
    "./routes/api/health.jsx": $api_health,
    "./routes/index.jsx": $index,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
